spring:
  datasource:
    username: root
    password: 1234567890xa
    url: jdbc:mysql://localhost:3306/hospitalcrm
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
       globally_quoted_identifiers: true
       jdbc:
         lob.non_contextual_creation: true
       dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
# change password to : 1234567890xa